max_samples: 100
max_length: 256
js: 
  - [10, 50, 70, 100, 120]
  - [11, 51, 71, 101, 121]
  - [12, 52, 72, 102, 122]

L: 2
k: 1
j_policy: "j==i"

cache_dir: "./cache"                # Directory containing pre-trained transport operators
skip_initial_n_samples_from_dataset: 10000